# Generated by Django 5.1.1 on 2024-11-14 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_waitlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 1, 3, 51, 778719, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
